# Form implementation generated from reading ui file 'dangkythanhvien.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 500)
        self.txtHo = QtWidgets.QLineEdit(parent=Dialog)
        self.txtHo.setGeometry(QtCore.QRect(50, 30, 150, 30))
        self.txtHo.setObjectName("txtHo")
        self.txtTen = QtWidgets.QLineEdit(parent=Dialog)
        self.txtTen.setGeometry(QtCore.QRect(220, 30, 150, 30))
        self.txtTen.setObjectName("txtTen")
        self.txtContact = QtWidgets.QLineEdit(parent=Dialog)
        self.txtContact.setGeometry(QtCore.QRect(50, 80, 320, 30))
        self.txtContact.setObjectName("txtContact")
        self.txtPassword = QtWidgets.QLineEdit(parent=Dialog)
        self.txtPassword.setGeometry(QtCore.QRect(50, 130, 320, 30))
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.cbDay = QtWidgets.QComboBox(parent=Dialog)
        self.cbDay.setGeometry(QtCore.QRect(50, 180, 80, 25))
        self.cbDay.setObjectName("cbDay")
        self.cbMonth = QtWidgets.QComboBox(parent=Dialog)
        self.cbMonth.setGeometry(QtCore.QRect(150, 180, 100, 25))
        self.cbMonth.setObjectName("cbMonth")
        self.cbYear = QtWidgets.QComboBox(parent=Dialog)
        self.cbYear.setGeometry(QtCore.QRect(270, 180, 100, 25))
        self.cbYear.setObjectName("cbYear")
        self.radNam = QtWidgets.QRadioButton(parent=Dialog)
        self.radNam.setGeometry(QtCore.QRect(50, 220, 80, 20))
        self.radNam.setObjectName("radNam")
        self.radNu = QtWidgets.QRadioButton(parent=Dialog)
        self.radNu.setGeometry(QtCore.QRect(150, 220, 80, 20))
        self.radNu.setObjectName("radNu")
        self.chkAgree = QtWidgets.QCheckBox(parent=Dialog)
        self.chkAgree.setGeometry(QtCore.QRect(50, 260, 300, 30))
        self.chkAgree.setObjectName("chkAgree")
        self.btnDangKy = QtWidgets.QPushButton(parent=Dialog)
        self.btnDangKy.setGeometry(QtCore.QRect(150, 320, 120, 40))
        self.btnDangKy.setObjectName("btnDangKy")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Đăng ký"))
        self.txtHo.setPlaceholderText(_translate("Dialog", "Họ"))
        self.txtTen.setPlaceholderText(_translate("Dialog", "Tên"))
        self.txtContact.setPlaceholderText(_translate("Dialog", "Số điện thoại hoặc email"))
        self.txtPassword.setPlaceholderText(_translate("Dialog", "Mật khẩu"))
        self.radNam.setText(_translate("Dialog", "Nam"))
        self.radNu.setText(_translate("Dialog", "Nữ"))
        self.chkAgree.setText(_translate("Dialog", "Tôi đồng ý với các điều khoản"))
        self.btnDangKy.setText(_translate("Dialog", "Đăng ký"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
